# Generated by Django 5.2.7 on 2025-11-04 06:57

import django.db.models.deletion
from django.db import migrations, models


def set_default_category(apps, schema_editor):
    """Set existing posts to the first available category"""
    Post = apps.get_model("blog", "Post")
    Category = apps.get_model("categories", "Category")

    # Get the first category (by ID or creation order)
    first_category = Category.objects.order_by("id").first()

    if first_category:
        Post.objects.filter(category__isnull=True).update(category_id=first_category.id)
    else:
        # No categories exist - create a default one
        default_category = Category.objects.create(name="uncategorized")
        Post.objects.filter(category__isnull=True).update(
            category_id=default_category.id
        )


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_author"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
            ),
        ),
        migrations.RunPython(
            set_default_category, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="categories.category"
            ),
        ),
    ]
