# Generated by Django 5.2.8 on 2025-11-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="blog_categories",
        ),
    ]
