# Generated by Django 5.2.6 on 2025-09-17 11:27

from django.db import migrations, models


def set_superuser_role(apps, schema_editor):
    user = apps.get_model("user", "User")
    user.objects.filter(is_superuser=True).update(role="admin")


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_user_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),

        migrations.RunPython(set_superuser_role, reverse_code=migrations.RunPython.noop),
    ]
